### ISSUE TITLE
feature request: different folder can be set different folder relative path

### ISSUE THREAD

**Issue by cpselvis** [erikdesjardins/zip-webpack-plugin#18]
For example:
imgs, css, javascript  is packaged in a folder,  html is in another folder. When zipped, hope to set them in different relative path.

Currently, zip-webpack-plugin can set only one relative path, I hope developer can use regular expression to set relative path

**Comment by erikdesjardins** [comment]
I think having a map of regexes (or something) would be too niche/specific, but I can implement a `pathMapper` option so you can do the mapping however you like:

```js
new ZipWebpackPlugin({
  pathMapper: function(assetPath) {
      if (path.dirname(assetPath) === 'html-folder') // assumes no subdirs
        return path.join('other-html-folder', path.basename(assetPath));
      return assetPath;
    },
})
```
