### ISSUE TITLE
Add option.exclude

### ISSUE THREAD

**Issue by monolithed** [erikdesjardins/zip-webpack-plugin#2]
Could you add an option to exclude some files?

```
{
   exclude: [....],
}
```

**Comment by erikdesjardins** [comment]
Yep, I should have some time over the next week to do this.

It'll likely be the same as the UglifyJSPlugin, i.e. `include` and `exclude` can be `string|RegExp|Array<string|RegExp>`

**Comment by monolithed** [comment]
Thanks!

**Comment by erikdesjardins** [comment]
Will be released shortly after I finish #3 (tonight)
