### ISSUE TITLE
Webpack 4 compatibility

### ISSUE THREAD

**Issue by grofzero** [erikdesjardins/zip-webpack-plugin#22]
hi,

Could you please add webpack 4 compatibility?
The plugin shows no errors, but doesn't create the zip file, and the whole output is swallowed,

Thank you very much,
grofzero

**Comment by wrldtrvllr** [comment]
Yes, this would be awesome!

**Comment by xoneill** [comment]
please do

**Comment by wrldtrvllr** [comment]
Hi,
I've created a pull request for this issue #23
