### ISSUE TITLE
Provide compression options

### ISSUE THREAD

**Issue by monolithed** [erikdesjardins/zip-webpack-plugin#3]
```
{
  mtime,
  mode,
  compress,
  forceZip64Format
}
```

Could you provide these [options](https://github.com/thejoshwolfe/yazl#addfilerealpath-metadatapath-options)?

**Comment by erikdesjardins** [comment]
Yep.

To clarify: you just want to specify it once for all files? (i.e. not a `(filePath: string) => CompressionOptions` callback)

**Comment by monolithed** [comment]
> To clarify: you just want to specify it once for all files?

Yep, thanks!
